@startuml 货运平台&园区系统上下文图

' System Context & System Landscape diagrams
' Import: !include http://c4.satc.ga/c4/C4_Context.puml
' Macros: Person, Person_Ext, System, System_Ext, SystemDb, SystemDb_Ext, Boundary, System_Boundary, Enterprise_Boundary
' Container diagram
' Import: !include http://c4.satc.ga/c4/C4_Container.puml
' Additional Macros: Container, ContainerDb, Container_Boundary
' Component diagram
' Import: !include http://c4.satc.ga/c4/C4_Component.puml
' Additional Macros: Component, ComponentDb
' Dynamic diagram
' Import: !include http://c4.satc.ga/c4/C4_Dynamic.puml
' Additional Macros: Interact, Interact2, GetIndex, SetIndex
' Deployment diagram
' Import: !include http://c4.satc.ga/c4/C4_Deployment.puml
' Additional Macros: Node

!include ../offline/C4_Context_cn.puml
' 图例
' LAYOUT_WITH_LEGEND() 
' 手稿，中文不友好
' LAYOUT_AS_SKETCH()
' LAYOUT_TOP_DOWN默认的
' LAYOUT_LEFT_RIGHT()
' 隐藏类型标签
HIDE_STEREOTYPE()

title 货运平台&园区系统上下文图

Person(user, "货办用户/货站用户")
Person_Ext(ext_user, "货代用户/航司/运输公司")
Enterprise_Boundary(eking, "易航科技") {
    System(clisp, "货运物流综合平台", "面向机场货运外部用户的业务办理和查询服务平台")
    System(walms, "货运园区管理系统", "提供园区基础数据维护，站台调度、停车场管理等服务")
}
Enterprise_Boundary(tsystem, "德电") {
    System(esb, "ESB系统", "RabbitMQ")
}
System_Ext(ext_system, "外部系统", "AODB\单一窗口\安检系统\三大货站系统\航司系统\货代系统\统一通信")

Rel(user, clisp, "使用", "HTTPS")
Rel(user, walms, "使用", "HTTPS")
Rel(ext_user, clisp, "使用", "HTTPS")
Rel(clisp, esb, "数据交互", "AMQP")
Rel(walms, esb, "数据交互", "AMQP")
Rel(esb, ext_system, "数据交互", "AMQP")


@enduml